<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \SearchHistory\Api\Representation\SearchRequestRepresentation $searchRequest
 * @var string $engine
 * @var string $query
 */

if (!$engine) {
    return;
}

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$partial = $plugins->get('partial');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()
    ->appendStylesheet($assetUrl('css/common-dialog.css', 'Common'))
    ->appendStylesheet($assetUrl('css/search-history.css', 'SearchHistory'));
$this->headScript()
    ->appendFile($assetUrl('js/common-dialog.js', 'Common'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/search-history.js', 'SearchHistory'), 'text/javascript', ['defer' => 'defer']);
?>

<div class="search-history search-history-actions">
    <button type="button" class="button delete search-history-button search-history-delete <?= $searchRequest ? '' : ' hidden' ?>" data-url="<?= $searchRequest ? $url('site/search-history-id', ['action' => 'delete', 'id' => $searchRequest->id()], true) : '' ?>" data-msg-success="<?= $escapeAttr($translate('Search deleted from your account.')) ?>">
        <span class="search-history-icon"><?= $translate('Delete saved search') ?></span>
    </button>
    <button type="button" class="button add search-history-button search-history-save<?= $searchRequest ? ' hidden' : '' ?>" data-msg-success="<?= $escapeAttr($translate('Search saved in your account.')) ?>" data-msg-no-query="<?= $escapeAttr('The current search has no query.') ?>">
        <span class="search-history-icon"><?= $translate('Save current search') ?></span>
    </button>
</div>

<?= $partial('common/dialog/search-history-save') ?>
