<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \SearchHistory\Api\Representation\SearchRequestRepresentation[] $searchRequests
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$assetUrl = $this->plugin('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$breadcrumbs = $plugins->has('breadcrumbs') ? $plugins->get('breadcrumbs') : null;
$user = $plugins->get('identity')();
$translatePlural = $plugins->get('translatePlural');
$guestNavigation = $user && $plugins->has('guestNavigation') ? $plugins->get('guestNavigation')() : null;

$hasGuestNav = $guestNavigation && $guestNavigation->getContainer()->count();

$this->headLink()
    ->appendStylesheet($assetUrl('css/common-dialog.css', 'Common'))
    ->appendStylesheet($assetUrl('css/search-history.css', 'SearchHistory'));
$this->headScript()
    ->appendFile($assetUrl('js/common-dialog.js', 'Common'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/search-history.js', 'SearchHistory'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'search-request browse');

$sortHeadings = [
    [
        'label' => $translate('Comment'),
        'value' => 'comment',
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created',
    ],
];
?>

<?php if ($breadcrumbs && !$hasGuestNav): ?>
<?= $breadcrumbs() ?>
<?php endif; ?>

<?php if ($hasGuestNav): ?>
<nav class="navigation-guest">
    <?= $guestNavigation->menu()->renderMenu() ?>
</nav>
<?php endif; ?>

<?= $this->pageTitle($translate('Search History'), 2); ?>

<?= $this->searchFilters() ?>

<div class="browse-controls">
    <?= $this->pagination() ?>
    <?= $this->sortSelector($sortHeadings) ?>
</div>

<?php if (count($searchRequests)): ?>
<h3><?= sprintf($translatePlural('%d saved search', '%d saved searches', $searchRequests), $searchRequests) ?></h3>

<?php $this->trigger('view.browse.before'); ?>
<ul class="search-request-list">
<?php foreach ($searchRequests as $searchRequest): ?>
    <li class="search-request">
        <h4><?= $hyperlink($searchRequest->comment(), $searchRequest->originalUrl()) ?></h4>
        <?= $hyperlink($translate('Delete'), $url('site/search-history-id', ['action' => 'delete', 'id' => $searchRequest->id()], true), ['class' => 'search-history-delete']) ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<?= $this->pagination() ?>

<?php else: ?>
<p>
    <?= $translate('No search requests are saved.') ?>
</p>
<?php endif; ?>
