<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \SearchHistory\Api\Representation\SearchRequestRepresentation[] $searchRequests
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$url = $plugins->get('url');
$assetUrl = $this->plugin('assetUrl');

$this->headLink()
    ->appendStylesheet($assetUrl('css/search-history.css', 'SearchHistory'));
$this->headScript()
    ->appendFile($assetUrl('js/search-history.js', 'SearchHistory'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'search-request browse');

$sortHeadings = [
    [
        'label' => $translate('Comment'),
        'value' => 'comment',
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created',
    ],
];
?>

<?= $this->pageTitle($translate('Search History'), 2); ?>

<?= $this->searchFilters() ?>

<div class="browse-controls">
    <?= $this->pagination() ?>
    <?= $this->sortSelector($sortHeadings) ?>
</div>

<?php if (count($searchRequests)): ?>
<h3><?= sprintf($translate('%d saved search requests'), count($searchRequests)) ?></h3>

<?php $this->trigger('view.browse.before'); ?>
<ul class="search-request-list">
<?php foreach ($searchRequests as $searchRequest): ?>
    <li class="search-request">
        <h4><?= $hyperlink($searchRequest->comment(), $searchRequest->originalUrl()) ?></h4>
        <?= $hyperlink($translate('Delete'), $url('site/search-history-id', ['action' => 'delete', 'id' => $searchRequest->id()], true), ['class' => 'search-history-delete']) ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<?= $this->pagination() ?>

<?php else: ?>
<p>
    <?= $translate('No search requests are saved.') ?>
</p>
<?php endif; ?>
